### ISSUE TITLE
Use single severity-level value to break the build

### ISSUE THREAD

**Issue by AlejandroRivera** [Redmart/sbt-checkstyle-plugin#5]
When executing `checkstyle-check`, the build will break if at least one issue is found that matches a list of severity levels provided by the user (defaulted to `["warning", "error"]`). It should be enough to specify `warning` to have anything above it break the build as well.

**Comment by JosephEarl** [comment]
Looking into this

**Comment by JosephEarl** [comment]
I reduced it down to a single value as part of https://github.com/etsy/sbt-checkstyle-plugin/issues/10. 

I skipped all the of `checkstyle-check` code if the level is "ignore" (since that seemed to have the . For the other levels, use a `Seq` of all levels then drop any values lower than the one specified
